name: Build application

on: push

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: pull code
        uses: actions/checkout@v2
      - name: Print Current Directory
        run: pwd
      - name: List Files in Directory
        run: ls
      - name: Check Dotnet Cli
        run: dotnet build
      - name: List Files after build
        run: ls LiftingLibrary.api/ -R
      - name: Check NPM cli
        run: npm -v
      
  
